/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2021-11-12 15:11:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/ramannpr/support_works/jaya-prakash/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/CommunityProtalWebsite/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1625549599528L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write(" \r\n");
      out.write("<head>\r\n");
      out.write("    <title>\r\n");
      out.write("        Community Portal Website\r\n");
      out.write("    </title>\r\n");
      out.write("\t\r\n");
      out.write("\t <style>\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("        }\r\n");
      out.write(" \r\n");
      out.write("        .navbar {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            position: sticky;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write(" \r\n");
      out.write("        .background {\r\n");
      out.write("            background: black;\r\n");
      out.write("            background-blend-mode: darken;\r\n");
      out.write("            background-size: cover;\r\n");
      out.write("        }\r\n");
      out.write(" \r\n");
      out.write("        .nav-list {\r\n");
      out.write("            width: 70%;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write(" \r\n");
      out.write("        .nav-list li {\r\n");
      out.write("            list-style: none;\r\n");
      out.write("            padding: 26px 30px;\r\n");
      out.write("        }\r\n");
      out.write(" \r\n");
      out.write("        .nav-list li a {\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write(" \r\n");
      out.write("        .nav-list li a:hover {\r\n");
      out.write("            color: grey;\r\n");
      out.write("        }\r\n");
      out.write("  \r\n");
      out.write("        .box-main {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            color: black;\r\n");
      out.write("            max-width: 80%;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            height: 605px;\r\n");
      out.write("        }\r\n");
      out.write(" \r\n");
      out.write("        .firsthalf {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("        }\r\n");
      out.write(" \r\n");
      out.write("        .heading-mission {\r\n");
      out.write("            font-family: 'Piazzolla', serif;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            font-size: 35px;\r\n");
      out.write("        }\r\n");
      out.write(" \r\n");
      out.write("        .text-mission {\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("\t\t\tpadding-bottom:100px;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t.heading-vission {\r\n");
      out.write("            font-family: 'Piazzolla', serif;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            font-size: 35px;\r\n");
      out.write("        }\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t.text-vision {\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("        }\r\n");
      out.write(" \r\n");
      out.write("        .text-footer {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            padding: 30px 0;\r\n");
      out.write("            font-family: 'Ubuntu', sans-serif;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write(" <body>\r\n");
      out.write(" <nav class=\"navbar background\">\r\n");
      out.write("        <ul class=\"nav-list\">\r\n");
      out.write("            <li><a href=\"http://localhost:8080/communityportal/user/portal/new\">Portal Details</a></li>\r\n");
      out.write("            <li><a href=\"http://localhost:8080/communityportal/user/register\">Register</a></li>\r\n");
      out.write("            <li><a href=\"http://localhost:8080/communityportal/user\">Login</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        \r\n");
      out.write("    </nav>\r\n");
      out.write(" \r\n");
      out.write("        <div class=\"box-main\">\r\n");
      out.write("            <div class=\"firstHalf\">\r\n");
      out.write("                <h1 class=\"heading-mission\">\r\n");
      out.write("                    Mission:\r\n");
      out.write("                </h1>\r\n");
      out.write("                <p class=\"text-mission\">\r\n");
      out.write("                    Community Portal is an award-winning and leading provider of software in the industry. \r\n");
      out.write("\t\t\t\t\tOur solutions boost productivity, lower costs and help users to communicate grow their businesses. \r\n");
      out.write("\t\t\t\t\tWe respect and value our team, and we look to bring the best talent together to make our future even stronger.\r\n");
      out.write("\t\t\t\t\tour Company's culture encourages employees to create, think and challenge each other in a fast-paced environment.\r\n");
      out.write("\t\t\t\t\tWe are determined to shape, not follow, \r\n");
      out.write("\t\t\t\t\tthe rapidly changing inindustry by transforming our products and services and identifying new ways to add value for our customers.\r\n");
      out.write("                </p>\r\n");
      out.write("\t\t\t\t <h1 class=\"heading-vission\">\r\n");
      out.write("                    Vision:\r\n");
      out.write("                </h1>\r\n");
      out.write("\t\t\t\t <p class=\"text-vision\">\r\n");
      out.write("                    Community Portal is about relationships, and technology and communication should make those relationships stronger. \r\n");
      out.write("\t\t\t\t\tThat's why, at this company, it's our mission to transform the way the industry operates by putting people at the heart of latest technology. \r\n");
      out.write("\t\t\t\t\tBy focusing on our customers,\r\n");
      out.write("\t\t\t\t\tdemanding operational excellence, and delivering results that make a difference, \r\n");
      out.write("\t\t\t\t\twe provide the level of trust and security that every thing will be end to end encyption.\r\n");
      out.write("                </p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write(" \r\n");
      out.write("  <footer class=\"background\">\r\n");
      out.write("        <p class=\"text-footer\">\r\n");
      out.write("            Copyright Â©-All rights are reserved\r\n");
      out.write("        </p>\r\n");
      out.write("    </footer>\r\n");
      out.write(" </body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
